export const searchterms = [
    'Genesis company history',
    'What is Genesis Inc?',
    'Genesis company products',
    'Genesis business model',
    'Genesis company reviews',
    'Genesis stock performance',
    'Genesis news and updates',
    'Genesis technology advancements',
    'Genesis customer service contact',
    'Genesis company headquarters location',
    'Genesis company founders',
    'Genesis market trends',
    'Genesis corporate culture',
    'Genesis financial statements',
    'Genesis company acquisitions',
    'Genesis future predictions',
    'Genesis CEO biography',
    'Genesis competitors in the market',
    'Genesis partnerships',
    'Genesis job openings',
    'Genesis company earnings report',
    'Genesis sustainability efforts',
    'Genesis corporate social responsibility',
    'Genesis annual reports',
    'Genesis office locations',
    'Genesis news release April 2025',
    'Genesis company tech innovations',
    'Genesis investment opportunities',
    'Genesis company sustainability initiatives',
    'Genesis patent filings',
    'Genesis company market share',
    'Genesis company press releases',
    'Genesis stock symbol and exchange',
    'Genesis annual growth rate',
    'Genesis mergers and acquisitions',
    'Genesis partnerships with tech firms',
    'Genesis financial outlook',
    'Genesis software solutions',
    'Genesis company diversity initiatives',
    'Genesis company leadership team',
    'Genesis company values and mission',
    'Genesis company products list',
    'Genesis global expansion plans',
    'Genesis headquarters history',
    'Genesis employee reviews',
    'Genesis company scandals',
    'Genesis industry recognition',
    'Genesis brand reputation',
    'Genesis marketing strategies',
    'Genesis company future predictions',
    'Genesis sales performance',
    'Genesis corporate sponsorships',
    'Genesis online store',
    'Genesis innovative projects',
    'Genesis technology news',
    'Genesis social media presence',
    'Genesis annual growth statistics',
    'Genesis leadership board',
    'Genesis charity donations',
    'Genesis brand identity',
    'Genesis ethical business practices',
    'Genesis customer satisfaction ratings',
    'Genesis financial growth forecast',
    'Genesis investor relations',
    'Genesis business strategy',
    'Genesis company patent history',
    'Genesis upcoming product launches',
    'Genesis reputation in the industry',
    'Genesis market analysis',
    'Genesis investor FAQ',
    'Genesis corporate governance',
    'Genesis industry awards',
    'Genesis company product recalls',
    'Genesis company history timeline',
    'Genesis company culture and values',
    'Genesis company security measures',
    'Genesis product reviews',
    'Genesis corporate transparency',
    'Genesis employee testimonials',
    'Genesis company\'s environmental impact',
    'Genesis leadership diversity',
    'Genesis stock price prediction',
    'Genesis supply chain management',
    'Genesis social media strategy',
    'Genesis company insights',
    'Genesis corporate sponsorships',
    'Genesis customer reviews on products',
    'Genesis sustainability and future goals',
    'Genesis tech breakthroughs',
    'Genesis company worldwide presence',
    'Genesis industry trends',
    'Genesis acquisition targets',
    'Genesis public relations',
    'Genesis stockholder communications',
    'Genesis manufacturing practices',
    'Genesis technological innovations',
    'Genesis press coverage',
    'Genesis company profile',
    'Genesis recent developments',
    'Genesis branding efforts',
    'news about the genesis company',
    'Genesis company announcements',
    'Genesis business news',
    'latest updates about Genesis Inc',
    'Genesis company tech news',
    'Genesis industry news',
    'Genesis press releases and updates',
    'Genesis global impact news',
    'Genesis company product news',
    'breaking news Genesis Inc',
    'Genesis stock market news',
    'Genesis company growth updates',
    'What is the future of Genesis Inc?',
    'Most innovative companies to watch in 2025',
    'Genesis company trends in the tech industry',
    'How is Genesis impacting the global market?',
    'Companies competing with Genesis in 2025',
    'What are the upcoming projects from Genesis?',
    'Which companies are disrupting the tech industry in 2025?',
    'The next big thing in tech – What’s Genesis working on?',
    'Genesis role in global technology innovation',
    'What companies are leading the market in 2025?',
    'How Genesis is shaping the future of technology',
    'Who are the top competitors to Genesis in 2025?',
    'What’s the growth forecast for Genesis in 2025?',
    'Tech companies to watch out for in 2025',
    'Companies leading the way in AI innovation 2025',
    'What’s new in the tech world? Genesis innovations',
    'Top technology companies for 2025 investments',
    'Will Genesis dominate the tech market in 2025?',
    'Latest developments in Genesis business strategy',
    'What’s next for the Genesis company?',
    'Market predictions for Genesis Inc in 2025',
    'How is Genesis adapting to future trends?',
    'Future of the tech industry: Is Genesis prepared?',
    'Which companies will be leaders in tech in 2025?',
    'What does Genesis’s future in AI look like?',
    'Is Genesis the next big thing in tech?',
    'What companies are making waves in the tech sector in 2025?',
    'Emerging technology companies to keep an eye on',
    'What are the key trends for Genesis in 2025?',
    'Genesis and the future of digital innovation',
    'What are the biggest challenges facing Genesis in 2025?',
    'Upcoming technology breakthroughs from Genesis',
    'How Genesis is pushing the limits of innovation',
    'Predictions for Genesis stock in 2025',
    'Technology predictions for Genesis in the next decade',
    'What are the top tech companies in the 2025 market?',
    'How Genesis is shaping the future of the tech industry',
    'Genesis company’s potential in emerging markets'
];
