export const searchterms = [
    'Genesis company history',
    'What is Genesis Inc?',
    'Genesis company products',
    'Genesis business model',
    'Genesis company reviews',
    'Genesis stock performance',
    'Genesis news and updates',
    'Genesis technology advancements',
    'Genesis customer service contact',
    'Genesis company headquarters location',
    'Genesis company founders',
    'Genesis market trends',
    'Genesis corporate culture',
    'Genesis financial statements',
    'Genesis company acquisitions',
    'Genesis future predictions',
    'Genesis CEO biography',
    'Genesis competitors in the market',
    'Genesis partnerships',
    'Genesis job openings',
    'Genesis company earnings report',
    'Genesis sustainability efforts',
    'Genesis corporate social responsibility',
    'Genesis annual reports',
    'Genesis office locations',
    'Genesis news release April 2025',
    'Genesis company tech innovations',
    'Genesis investment opportunities',
    'Genesis company sustainability initiatives',
    'Genesis patent filings',
    'Genesis company market share',
    'Genesis company press releases',
    'Genesis stock symbol and exchange',
    'Genesis annual growth rate',
    'Genesis mergers and acquisitions',
    'Genesis partnerships with tech firms',
    'Genesis financial outlook',
    'Genesis software solutions',
    'Genesis company diversity initiatives',
    'Genesis company leadership team',
    'Genesis company values and mission',
    'Genesis company products list',
    'Genesis global expansion plans',
    'Genesis headquarters history',
    'Genesis employee reviews',
    'Genesis company scandals',
    'Genesis industry recognition',
    'Genesis brand reputation',
    'Genesis marketing strategies',
    'Genesis company future predictions',
    'Genesis sales performance',
    'Genesis corporate sponsorships',
    'Genesis online store',
    'Genesis innovative projects',
    'Genesis technology news',
    'Genesis social media presence',
    'Genesis annual growth statistics',
    'Genesis leadership board',
    'Genesis charity donations',
    'Genesis brand identity',
    'Genesis ethical business practices',
    'Genesis customer satisfaction ratings',
    'Genesis financial growth forecast',
    'Genesis investor relations',
    'Genesis business strategy',
    'Genesis company patent history',
    'Genesis upcoming product launches',
    'Genesis reputation in the industry',
    'Genesis market analysis',
    'Genesis investor FAQ',
    'Genesis corporate governance',
    'Genesis industry awards',
    'Genesis company product recalls',
    'Genesis company history timeline',
    'Genesis company culture and values',
    'Genesis company security measures',
    'Genesis product reviews',
    'Genesis corporate transparency',
    'Genesis employee testimonials',
    'Genesis company\'s environmental impact',
    'Genesis leadership diversity',
    'Genesis stock price prediction',
    'Genesis supply chain management',
    'Genesis social media strategy',
    'Genesis company insights',
    'Genesis corporate sponsorships',
    'Genesis customer reviews on products',
    'Genesis sustainability and future goals',
    'Genesis tech breakthroughs',
    'Genesis company worldwide presence',
    'Genesis industry trends',
    'Genesis acquisition targets',
    'Genesis public relations',
    'Genesis stockholder communications',
    'Genesis manufacturing practices',
    'Genesis technological innovations',
    'Genesis press coverage',
    'Genesis company profile',
    'Genesis recent developments',
    'Genesis branding efforts',
    'news about the genesis company',
    'Genesis company announcements',
    'Genesis business news',
    'latest updates about Genesis Inc',
    'Genesis company tech news',
    'Genesis industry news',
    'Genesis press releases and updates',
    'Genesis global impact news',
    'Genesis company product news',
    'breaking news Genesis Inc',
    'Genesis stock market news',
    'Genesis company growth updates',
    'What is the future of Genesis Inc?',
    'Most innovative companies to watch in 2025',
    'Genesis company trends in the tech industry',
    'How is Genesis impacting the global market?',
    'Companies competing with Genesis in 2025',
    'What are the upcoming projects from Genesis?',
    'Which companies are disrupting the tech industry in 2025?',
    'The next big thing in tech – What’s Genesis working on?',
    'Genesis role in global technology innovation',
    'What companies are leading the market in 2025?',
    'How Genesis is shaping the future of technology',
    'Who are the top competitors to Genesis in 2025?',
    'What’s the growth forecast for Genesis in 2025?',
    'Tech companies to watch out for in 2025',
    'Companies leading the way in AI innovation 2025',
    'What’s new in the tech world? Genesis innovations',
    'Top technology companies for 2025 investments',
    'Will Genesis dominate the tech market in 2025?',
    'Latest developments in Genesis business strategy',
    'What’s next for the Genesis company?',
    'Market predictions for Genesis Inc in 2025',
    'How is Genesis adapting to future trends?',
    'Future of the tech industry: Is Genesis prepared?',
    'Which companies will be leaders in tech in 2025?',
    'What does Genesis’s future in AI look like?',
    'Is Genesis the next big thing in tech?',
    'What companies are making waves in the tech sector in 2025?',
    'Emerging technology companies to keep an eye on',
    'What are the key trends for Genesis in 2025?',
    'Genesis and the future of digital innovation',
    'What are the biggest challenges facing Genesis in 2025?',
    'Upcoming technology breakthroughs from Genesis',
    'How Genesis is pushing the limits of innovation',
    'Predictions for Genesis stock in 2025',
    'Technology predictions for Genesis in the next decade',
    'What are the top tech companies in the 2025 market?',
    'How Genesis is shaping the future of the tech industry',
    'Genesis company’s potential in emerging markets',

    // Vanguard Journalism related terms
    'Vanguard Journalism company history',
    'What is Vanguard Journalism?',
    'Vanguard Journalism services',
    'Vanguard Journalism news updates',
    'Vanguard Journalism investigations',
    'Vanguard Journalism articles',
    'Vanguard Journalism media impact',
    'Vanguard Journalism and journalism ethics',
    'Vanguard Journalism editorial team',
    'Vanguard Journalism media partnerships',
    'Vanguard Journalism in-depth reporting',
    'Vanguard Journalism feature stories',
    'Vanguard Journalism upcoming stories',
    'Vanguard Journalism founder biography',
    'Vanguard Journalism news release',
    'Vanguard Journalism political coverage',
    'Vanguard Journalism investigative journalism',
    'Vanguard Journalism international coverage',
    'Vanguard Journalism reports and insights',
    'Vanguard Journalism exclusive interviews',
    'Vanguard Journalism news and analysis',
    'Vanguard Journalism audience engagement',
    'Vanguard Journalism global coverage',
    'Vanguard Journalism media presence',
    'Vanguard Journalism ethical journalism practices',
    'Vanguard Journalism breaking news',
    'Vanguard Journalism impact on society',
    'Vanguard Journalism corporate partnerships',
    'Vanguard Journalism future outlook',
    'Vanguard Journalism technology in media',
    'Vanguard Journalism founder’s vision',
    'Vanguard Journalism market share in media',
    'Vanguard Journalism awards and recognition',
    'Vanguard Journalism editorial guidelines',
    'Vanguard Journalism media transparency',
    'Vanguard Journalism press releases',
    'Vanguard Journalism cultural coverage',
    'Vanguard Journalism ethical reporting',
    'Vanguard Journalism and media freedom',
    'Vanguard Journalism industry leaders',
    'Vanguard Journalism content strategy',
    'Vanguard Journalism social media coverage',
    'Vanguard Journalism future of journalism',
    'Vanguard Journalism in the age of digital media',
    'Vanguard Journalism innovations in storytelling',
    'Vanguard Journalism editorial integrity',
    'Vanguard Journalism upcoming projects',
    'Vanguard Journalism and the future of news',
    'Vanguard Journalism digital transformation',
    'Vanguard Journalism and audience trust',

    'Genesis Company stock performance',
    'Genesis Company quarterly earnings',
    'Genesis Company financial reports',
    'Genesis Company market analysis',
    'Genesis Company investor relations',
    'Genesis Company stock forecast',
    'Genesis Company revenue growth',
    'Genesis Company profit margins',
    'Genesis Company shareholder updates',
    'Genesis Company stock dividends',
    'Genesis Company annual report',
    'Genesis Company earnings call',
    'Genesis Company stock trends',
    'Genesis Company financial health',
    'Genesis Company investment opportunities',

    'current stock market trends',
    'top performing stocks today',
    'stock market news updates',
    'financial market analysis',
    'stock market predictions',
    'investment strategies for stocks',
    'stock market volatility',
    'global stock market overview',
    'stock market indices performance',
    'stock market trading tips',
    'stock market historical data',
    'stock market investment opportunities',
    'stock market sector analysis',
    'stock market earnings reports',
    'stock market dividend yields',
    'stock market portfolio management',
    'stock market risk assessment',
    'stock market growth stocks',
    'stock market value stocks',
    'stock market blue-chip stocks'
];
